{
 "title": "Golang metrics v3",
 "description": "Process status published by Go Prometheus client library, e.g. memory used, fds open, GC details",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "proxy",
    "query": {
     "query": "{job=~\"cloudgate_proxy\"}"
    }
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" },
   { "name": "job", "query": { "query": "process_resident_memory_bytes" } },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(go_memstats_alloc_bytes, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "process memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Resident Memory" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=~\"^($namespace)$\",instance=~\"^($proxy)$\",job=~\"^($job)$\"}",
     "legendFormat": "{{job}} - {{instance}} - resident"
    },
    {
     "expr": "process_virtual_memory_bytes{namespace=~\"^($namespace)$\",instance=~\"^($proxy)$\",job=~\"^($job)$\"}",
     "legendFormat": "{{job}} - {{instance}} - virtual"
    }
   ]
  },
  {
   "title": "process memory deriv",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{namespace=~\"^($namespace)$\",instance=~\"^($proxy)$\",job=~\"^($job)$\"}[$interval])",
     "legendFormat": "{{job}} - {{instance}} - resident"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes{namespace=~\"^($namespace)$\",instance=~\"^($proxy)$\",job=~\"^($job)$\"}[$interval])",
     "legendFormat": "{{job}} - {{instance}} - virtual"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{namespace=~\"^($namespace)$\",instance=~\"^($proxy)$\",job=~\"^($job)$\"}",
     "legendFormat": "{{job}} - {{instance}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{namespace=~\"^($namespace)$\",instance=~\"^($proxy)$\",job=~\"^($job)$\"}[30s])",
     "legendFormat": "{{job}} - {{instance}} - alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{namespace=~\"^($namespace)$\",instance=~\"^($proxy)$\",job=~\"^($job)$\"}",
     "legendFormat": "{{job}} - {{instance}} - stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{namespace=~\"^($namespace)$\",instance=~\"^($proxy)$\",job=~\"^($job)$\"}",
     "legendFormat": "{{job}} - {{instance}} - heap inuse"
    }
   ]
  },
  {
   "title": "go memstats deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes{namespace=~\"^($namespace)$\",instance=~\"^($proxy)$\",job=~\"^($job)$\"}[$interval])",
     "legendFormat": "{{job}} - {{instance}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{namespace=~\"^($namespace)$\",instance=~\"^($proxy)$\",job=~\"^($job)$\"}[$interval])",
     "legendFormat": "{{job}} - {{instance}} - alloc rate"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes{namespace=~\"^($namespace)$\",instance=~\"^($proxy)$\",job=~\"^($job)$\"}[$interval])",
     "legendFormat": "{{job}} - {{instance}} - stack inuse"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes{namespace=~\"^($namespace)$\",instance=~\"^($proxy)$\",job=~\"^($job)$\"}[$interval])",
     "legendFormat": "{{job}} - {{instance}} - heap inuse"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{namespace=~\"^($namespace)$\",instance=~\"^($proxy)$\",job=~\"^($job)$\"}",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "open fds deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(process_open_fds{namespace=~\"^($namespace)$\",instance=~\"^($proxy)$\",job=~\"^($job)$\"}[$interval])",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{namespace=~\"^($namespace)$\",instance=~\"^($proxy)$\",job=~\"^($job)$\"}",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{namespace=~\"^($namespace)$\",instance=~\"^($proxy)$\",job=~\"^($job)$\"}",
     "legendFormat": "{{job}} - {{instance}}: {{quantile}}"
    }
   ]
  }
 ]
}