{
 "title": "Proxy Migrator (dashboard v6)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "proxyinstance",
    "query": {
     "query": "{job=~\"cloudgate_proxy\"}"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "{job=~\"cloudgate_proxy\"}"
    }
   },
   { "name": "histogram_rate", "label": "Histogram Interval", "query": "30s,1m,2m,3m,4m,5m" }
  ]
 },
 "panels": [
  { "title": "Proxy level metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "\"Origin\" throughput (requests per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(cloudgate_proxy_request_duration_seconds_count{destination=\"origin\",instance=~\"^($proxyinstance)$\"}[5m])"
    }
   ]
  },
  {
   "title": "\"Both\" throughput (requests per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(cloudgate_proxy_request_duration_seconds_count{destination=\"both\",instance=~\"^($proxyinstance)$\"}[5m])"
    }
   ]
  },
  {
   "title": "Target throughput (requests per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(cloudgate_proxy_request_duration_seconds_count{destination=\"target\",instance=~\"^($proxyinstance)$\"}[5m])"
    }
   ]
  },
  {
   "title": "Origin Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"origin\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} origin_seconds_p50"
    },
    {
     "expr": "histogram_quantile(0.99, rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"origin\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} origin_seconds_p99"
    },
    {
     "expr": "histogram_quantile(0.999, rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"origin\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} origin_seconds_p999"
    },
    {
     "expr": "histogram_quantile(0.90, rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"origin\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} origin_seconds_p90"
    },
    {
     "expr": "histogram_quantile(0.95, rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"origin\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} origin_seconds_p95"
    },
    {
     "expr": "histogram_quantile(0.75, rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"origin\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} origin_seconds_p75"
    }
   ]
  },
  {
   "title": "Both Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"both\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} both_seconds_p50"
    },
    {
     "expr": "histogram_quantile(0.99, rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"both\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} both_seconds_p99"
    },
    {
     "expr": "histogram_quantile(0.999, rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"both\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} both_seconds_p999"
    },
    {
     "expr": "histogram_quantile(0.90, rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"both\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} both_seconds_p90"
    },
    {
     "expr": "histogram_quantile(0.95, rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"both\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} both_seconds_p95"
    },
    {
     "expr": "histogram_quantile(0.75, rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"both\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} both_seconds_p75"
    }
   ]
  },
  {
   "title": "Target Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"target\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} target_seconds_p50"
    },
    {
     "expr": "histogram_quantile(0.99, rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"target\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} target_seconds_p99"
    },
    {
     "expr": "histogram_quantile(0.999, rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"target\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} target_seconds_p999"
    },
    {
     "expr": "histogram_quantile(0.90, rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"target\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} target_seconds_p90"
    },
    {
     "expr": "histogram_quantile(0.95, rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"target\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} target_seconds_p95"
    },
    {
     "expr": "histogram_quantile(0.75, rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"target\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} target_seconds_p75"
    }
   ]
  },
  {
   "title": "Origin latency Aggregate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"origin\"}[$histogram_rate])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"origin\"}[$histogram_rate])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"origin\"}[$histogram_rate])) by (le))",
     "legendFormat": "p999"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"origin\"}[$histogram_rate])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"origin\"}[$histogram_rate])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"origin\"}[$histogram_rate])) by (le))",
     "legendFormat": "p75"
    }
   ]
  },
  {
   "title": "Both latency Aggregate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"both\"}[$histogram_rate])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"both\"}[$histogram_rate])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"both\"}[$histogram_rate])) by (le))",
     "legendFormat": "p999"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"both\"}[$histogram_rate])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"both\"}[$histogram_rate])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"both\"}[$histogram_rate])) by (le))",
     "legendFormat": "p75"
    }
   ]
  },
  {
   "title": "Target latency Aggregate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"target\"}[$histogram_rate])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"target\"}[$histogram_rate])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"target\"}[$histogram_rate])) by (le))",
     "legendFormat": "p999"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"target\"}[$histogram_rate])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"target\"}[$histogram_rate])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(cloudgate_proxy_request_duration_seconds_bucket{destination=\"target\"}[$histogram_rate])) by (le))",
     "legendFormat": "p75"
    }
   ]
  },
  {
   "title": "Client Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudgate_client_connections_total{instance=~\"^($proxyinstance)$\"}",
     "legendFormat": "client_connections {instance=\"{{instance}}\"}"
    }
   ]
  },
  {
   "title": "In flight requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudgate_proxy_inflight_requests_total{instance=~\"^($proxyinstance)$\"}",
     "legendFormat": "inflight_requests {instance=\"{{instance}}\", destination=\"{{destination}}\"}"
    }
   ]
  },
  {
   "title": "PS Cache misses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudgate_pscache_miss_total{instance=~\"^($proxyinstance)$\"}",
     "legendFormat": "pscache_miss_total {instance=\"{{instance}}\"}"
    }
   ]
  },
  {
   "title": "PS Cache entries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudgate_pscache_entries_total{instance=~\"^($proxyinstance)$\"}",
     "legendFormat": "pscache_entries {instance=\"{{instance}}\"}"
    }
   ]
  },
  { "title": "Node level metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Origin throughput (requests per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(cloudgate_origin_request_duration_seconds_count{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[5m])"
    }
   ]
  },
  {
   "title": "Target throughput (requests per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(cloudgate_target_request_duration_seconds_count{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[5m])"
    }
   ]
  },
  {
   "title": "Origin latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(cloudgate_origin_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p50"
    },
    {
     "expr": "histogram_quantile(0.99, rate(cloudgate_origin_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p99"
    },
    {
     "expr": "histogram_quantile(0.999, rate(cloudgate_origin_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p999"
    },
    {
     "expr": "histogram_quantile(0.95, rate(cloudgate_origin_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p95"
    },
    {
     "expr": "histogram_quantile(0.90, rate(cloudgate_origin_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p90"
    },
    {
     "expr": "histogram_quantile(0.75, rate(cloudgate_origin_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p75"
    }
   ]
  },
  {
   "title": "Target latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(cloudgate_target_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p50"
    },
    {
     "expr": "histogram_quantile(0.99, rate(cloudgate_target_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p99"
    },
    {
     "expr": "histogram_quantile(0.999, rate(cloudgate_target_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p999"
    },
    {
     "expr": "histogram_quantile(0.95, rate(cloudgate_target_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p95"
    },
    {
     "expr": "histogram_quantile(0.90, rate(cloudgate_target_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p90"
    },
    {
     "expr": "histogram_quantile(0.75, rate(cloudgate_target_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p75"
    }
   ]
  },
  {
   "title": "Origin latency Aggregate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(cloudgate_origin_request_duration_seconds_bucket[$histogram_rate])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cloudgate_origin_request_duration_seconds_bucket[$histogram_rate])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(cloudgate_origin_request_duration_seconds_bucket[$histogram_rate])) by (le))",
     "legendFormat": "p999"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cloudgate_origin_request_duration_seconds_bucket[$histogram_rate])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(cloudgate_origin_request_duration_seconds_bucket[$histogram_rate])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(cloudgate_origin_request_duration_seconds_bucket[$histogram_rate])) by (le))",
     "legendFormat": "p75"
    }
   ]
  },
  {
   "title": "Target latency Aggregate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(cloudgate_target_request_duration_seconds_bucket[$histogram_rate])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cloudgate_target_request_duration_seconds_bucket[$histogram_rate])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(cloudgate_target_request_duration_seconds_bucket[$histogram_rate])) by (le))",
     "legendFormat": "p999"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cloudgate_target_request_duration_seconds_bucket[$histogram_rate])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(cloudgate_target_request_duration_seconds_bucket[$histogram_rate])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(cloudgate_target_request_duration_seconds_bucket[$histogram_rate])) by (le))",
     "legendFormat": "p75"
    }
   ]
  },
  {
   "title": "Origin Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudgate_origin_connections_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}",
     "legendFormat": "origin_connections {instance=\"{{instance}}\", node=\"{{node}}\"}"
    }
   ]
  },
  {
   "title": "Target Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudgate_target_connections_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}",
     "legendFormat": "target_connections {instance=\"{{instance}}\", node=\"{{node}}\"}"
    }
   ]
  },
  {
   "title": "Origin Connections Sums",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cloudgate_origin_connections_total) by (node)",
     "legendFormat": "origin_connections {node=\"{{node}}\"}"
    },
    {
     "expr": "sum(cloudgate_origin_connections_total) by (instance)",
     "legendFormat": "origin_connections {instance=\"{{instance}}\"}"
    }
   ]
  },
  {
   "title": "Target Connections Sums",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cloudgate_target_connections_total) by (node)",
     "legendFormat": "target_connections {node=\"{{node}}\"}"
    },
    {
     "expr": "sum(cloudgate_target_connections_total) by (instance)",
     "legendFormat": "target_connections {instance=\"{{instance}}\"}"
    }
   ]
  },
  {
   "title": "Origin Errors Sums",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (error) (cloudgate_origin_requests_failed_total)"
    },
    {
     "expr": "sum by (instance) (cloudgate_origin_requests_failed_total)"
    },
    {
     "expr": "sum by (node) (cloudgate_origin_requests_failed_total)"
    }
   ]
  },
  {
   "title": "Target Errors Sums",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (error) (cloudgate_target_requests_failed_total)"
    },
    {
     "expr": "sum by (instance) (cloudgate_target_requests_failed_total)"
    },
    {
     "expr": "sum by (node) (cloudgate_target_requests_failed_total)"
    }
   ]
  },
  {
   "title": "Origin Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudgate_origin_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\", error=\"{{error}}\"}"
    }
   ]
  },
  {
   "title": "Target Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudgate_target_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\", error=\"{{error}}\"}"
    }
   ]
  },
  {
   "title": "Origin Errors Sum by Instance and Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, node) (cloudgate_origin_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"})"
    }
   ]
  },
  {
   "title": "Target Errors Sum by Instance and Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, node) (cloudgate_target_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"})"
    }
   ]
  },
  {
   "title": "Origin Errors Sum by Instance and Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, error) (cloudgate_origin_requests_failed_total{instance=~\"^($proxyinstance)$\"})"
    }
   ]
  },
  {
   "title": "Target Errors Sum by Instance and Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, error) (cloudgate_target_requests_failed_total{instance=~\"^($proxyinstance)$\"})"
    }
   ]
  },
  {
   "title": "Origin Errors Sum by Node and Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node, error) (cloudgate_origin_requests_failed_total{node=~\"^($node)$\"})"
    }
   ]
  },
  {
   "title": "Target Errors Sum by Node and Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node, error) (cloudgate_target_requests_failed_total{node=~\"^($node)$\"})"
    }
   ]
  }
 ]
}