{
 "title": "ZDM Proxy Dashboard v1",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "proxyinstance",
    "query": {
     "query": "{job=~\"zdm_proxy\"}"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "{job=~\"zdm_proxy\"}"
    }
   },
   { "name": "histogram_rate", "label": "Histogram Interval", "query": "1m,2m,3m,4m,5m" },
   { "name": "error_rate", "label": "Error Rate interval", "query": "1m,2m,3m,4m,5m" }
  ]
 },
 "panels": [
  { "title": "Proxy level metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Origin Read Throughput (requests per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(zdm_proxy_request_duration_seconds_count{type=\"reads_origin\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])"
    }
   ]
  },
  {
   "title": "Write Throughput (requests per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(zdm_proxy_request_duration_seconds_count{type=\"writes\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])"
    }
   ]
  },
  {
   "title": "Target Read Throughput (requests per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(zdm_proxy_request_duration_seconds_count{type=\"reads_target\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])"
    }
   ]
  },
  {
   "title": "Origin Read Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_origin\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} origin_seconds_p50"
    },
    {
     "expr": "histogram_quantile(0.99, rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_origin\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} origin_seconds_p99"
    },
    {
     "expr": "histogram_quantile(0.999, rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_origin\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} origin_seconds_p999"
    },
    {
     "expr": "histogram_quantile(0.90, rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_origin\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} origin_seconds_p90"
    },
    {
     "expr": "histogram_quantile(0.95, rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_origin\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} origin_seconds_p95"
    },
    {
     "expr": "histogram_quantile(0.75, rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_origin\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} origin_seconds_p75"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(zdm_proxy_request_duration_seconds_bucket{type=\"writes\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} both_seconds_p50"
    },
    {
     "expr": "histogram_quantile(0.99, rate(zdm_proxy_request_duration_seconds_bucket{type=\"writes\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} both_seconds_p99"
    },
    {
     "expr": "histogram_quantile(0.999, rate(zdm_proxy_request_duration_seconds_bucket{type=\"writes\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} both_seconds_p999"
    },
    {
     "expr": "histogram_quantile(0.90, rate(zdm_proxy_request_duration_seconds_bucket{type=\"writes\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} both_seconds_p90"
    },
    {
     "expr": "histogram_quantile(0.95, rate(zdm_proxy_request_duration_seconds_bucket{type=\"writes\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} both_seconds_p95"
    },
    {
     "expr": "histogram_quantile(0.75, rate(zdm_proxy_request_duration_seconds_bucket{type=\"writes\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} both_seconds_p75"
    }
   ]
  },
  {
   "title": "Target Read Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_target\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} target_seconds_p50"
    },
    {
     "expr": "histogram_quantile(0.99, rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_target\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} target_seconds_p99"
    },
    {
     "expr": "histogram_quantile(0.999, rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_target\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} target_seconds_p999"
    },
    {
     "expr": "histogram_quantile(0.90, rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_target\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} target_seconds_p90"
    },
    {
     "expr": "histogram_quantile(0.95, rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_target\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} target_seconds_p95"
    },
    {
     "expr": "histogram_quantile(0.75, rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_target\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
     "legendFormat": "{{instance}} target_seconds_p75"
    }
   ]
  },
  {
   "title": "Origin Read Latency Aggregate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_origin\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_origin\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_origin\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p999"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_origin\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_origin\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_origin\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p75"
    }
   ]
  },
  {
   "title": "Write Latency Aggregate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"writes\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"writes\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"writes\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p999"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"writes\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"writes\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"writes\"}[$histogram_rate])) by (le))",
     "legendFormat": "p75"
    }
   ]
  },
  {
   "title": "Target Read Latency Aggregate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_target\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_target\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_target\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p999"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_target\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_target\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_target\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p75"
    }
   ]
  },
  {
   "title": "Client Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zdm_client_connections_total{instance=~\"^($proxyinstance)$\"}",
     "legendFormat": "client_connections {instance=\"{{instance}}\"}"
    }
   ]
  },
  {
   "title": "In flight requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zdm_proxy_inflight_requests_total{instance=~\"^($proxyinstance)$\"}",
     "legendFormat": "inflight_requests {instance=\"{{instance}}\", type=\"{{type}}\"}"
    }
   ]
  },
  {
   "title": "PS Cache misses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zdm_pscache_miss_total{instance=~\"^($proxyinstance)$\"}",
     "legendFormat": "pscache_miss_total {instance=\"{{instance}}\"}"
    }
   ]
  },
  {
   "title": "PS Cache entries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zdm_pscache_entries_total{instance=~\"^($proxyinstance)$\"}",
     "legendFormat": "pscache_entries {instance=\"{{instance}}\"}"
    }
   ]
  },
  { "title": "Node level metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Origin Throughput (requests per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(zdm_origin_request_duration_seconds_count{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])"
    }
   ]
  },
  {
   "title": "Target Throughput (requests per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(zdm_target_request_duration_seconds_count{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])"
    }
   ]
  },
  {
   "title": "Origin Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(zdm_origin_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p50"
    },
    {
     "expr": "histogram_quantile(0.99, rate(zdm_origin_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p99"
    },
    {
     "expr": "histogram_quantile(0.999, rate(zdm_origin_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p999"
    },
    {
     "expr": "histogram_quantile(0.95, rate(zdm_origin_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p95"
    },
    {
     "expr": "histogram_quantile(0.90, rate(zdm_origin_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p90"
    },
    {
     "expr": "histogram_quantile(0.75, rate(zdm_origin_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p75"
    }
   ]
  },
  {
   "title": "Target Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(zdm_target_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p50"
    },
    {
     "expr": "histogram_quantile(0.99, rate(zdm_target_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p99"
    },
    {
     "expr": "histogram_quantile(0.999, rate(zdm_target_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p999"
    },
    {
     "expr": "histogram_quantile(0.95, rate(zdm_target_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p95"
    },
    {
     "expr": "histogram_quantile(0.90, rate(zdm_target_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p90"
    },
    {
     "expr": "histogram_quantile(0.75, rate(zdm_target_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p75"
    }
   ]
  },
  {
   "title": "Origin Latency Aggregate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(zdm_origin_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(zdm_origin_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(zdm_origin_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p999"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(zdm_origin_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(zdm_origin_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(zdm_origin_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p75"
    }
   ]
  },
  {
   "title": "Target Latency Aggregate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(zdm_target_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(zdm_target_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(zdm_target_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p999"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(zdm_target_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(zdm_target_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(zdm_target_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p75"
    }
   ]
  },
  {
   "title": "Origin Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zdm_origin_connections_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}",
     "legendFormat": "origin_connections {instance=\"{{instance}}\", node=\"{{node}}\"}"
    }
   ]
  },
  {
   "title": "Target Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zdm_target_connections_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}",
     "legendFormat": "target_connections {instance=\"{{instance}}\", node=\"{{node}}\"}"
    }
   ]
  },
  {
   "title": "Origin Connections Sums",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(zdm_origin_connections_total{node=~\"^($node)$\"}) by (node)",
     "legendFormat": "origin_connections {node=\"{{node}}\"}"
    },
    {
     "expr": "sum(zdm_origin_connections_total{node=~\"^($node)$\"}) by (instance)",
     "legendFormat": "origin_connections {instance=\"{{instance}}\"}"
    }
   ]
  },
  {
   "title": "Target Connections Sums",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(zdm_target_connections_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}) by (node)",
     "legendFormat": "target_connections {node=\"{{node}}\"}"
    },
    {
     "expr": "sum(zdm_target_connections_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}) by (instance)",
     "legendFormat": "target_connections {instance=\"{{instance}}\"}"
    }
   ]
  },
  {
   "title": "Origin Error Rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(zdm_origin_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate])",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\", error=\"{{error}}\"}"
    }
   ]
  },
  {
   "title": "Target Error Rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(zdm_target_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate])",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\", error=\"{{error}}\"}"
    }
   ]
  },
  {
   "title": "Origin Error Rate Sums",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (error)(rate(zdm_origin_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate]))"
    },
    {
     "expr": "sum by (instance) (rate(zdm_origin_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate]))"
    },
    {
     "expr": "sum by (node) (rate(zdm_origin_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate]))"
    }
   ]
  },
  {
   "title": "Origin Error Rates by Node and Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node, error) (rate(zdm_origin_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate]))"
    }
   ]
  },
  {
   "title": "Target Error Rate Sums",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (error)(rate(zdm_target_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate]))"
    },
    {
     "expr": "sum by (instance) (rate(zdm_target_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate]))"
    },
    {
     "expr": "sum by (node) (rate(zdm_target_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate]))"
    }
   ]
  },
  {
   "title": "Target Error Rates by Node and Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node, error) (rate(zdm_target_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate]))"
    }
   ]
  },
  {
   "title": "Origin Error Rates by Instance and Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, error) (rate(zdm_origin_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate]))"
    }
   ]
  },
  {
   "title": "Origin Error Rates by Instance and Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, node) (rate(zdm_origin_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate]))"
    }
   ]
  },
  {
   "title": "Target Error Rates by Instance and Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, error) (rate(zdm_target_requests_failed_total{instance=~\"^($proxyinstance)$\", node=~\"^($node)$\"}[$error_rate]))"
    }
   ]
  },
  {
   "title": "Target Error Rates by Instance and Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, node) (rate(zdm_target_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate]))"
    }
   ]
  },
  {
   "title": "Origin Error Counters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zdm_origin_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\", error=\"{{error}}\"}"
    }
   ]
  },
  {
   "title": "Target Error Counters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zdm_target_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\", error=\"{{error}}\"}"
    }
   ]
  },
  {
   "title": "Origin Error Counter Sums",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (error)(zdm_origin_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"})"
    },
    {
     "expr": "sum by (instance) (zdm_origin_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"})"
    },
    {
     "expr": "sum by (node) (zdm_origin_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"})"
    }
   ]
  },
  {
   "title": "Origin Error Counters by Node and Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node, error) (zdm_origin_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"})"
    }
   ]
  },
  {
   "title": "Target Error Counter Sums",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (error)(zdm_target_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"})"
    },
    {
     "expr": "sum by (instance) (zdm_target_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"})"
    },
    {
     "expr": "sum by (node) (zdm_target_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"})"
    }
   ]
  },
  {
   "title": "Target Error Counters by Node and Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node, error) (zdm_target_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"})"
    }
   ]
  },
  {
   "title": "Origin Error Counters by Instance and Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, error) (zdm_origin_requests_failed_total{instance=~\"^($proxyinstance)$\", node=~\"^($node)$\"})"
    }
   ]
  },
  {
   "title": "Origin Error Counters by Instance and Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, node) (zdm_origin_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"})"
    }
   ]
  },
  {
   "title": "Target Error Counters by Instance and Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, error) (zdm_target_requests_failed_total{instance=~\"^($proxyinstance)$\", node=~\"^($node)$\"})"
    }
   ]
  },
  {
   "title": "Target Error Counters by Instance and Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, node) (zdm_target_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"})"
    }
   ]
  },
  { "title": "Async Read Request Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 131 } },
  {
   "title": "In Flight Async Read Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zdm_async_inflight_requests_total{instance=~\"^($proxyinstance)$\", node=~\"^($node)$\"}",
     "legendFormat": "async_inflight_requests {instance=\"{{instance}}\", node=\"{{node}}\"}"
    }
   ]
  },
  {
   "title": "Async Read Throughput (requests per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 132 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(zdm_async_request_duration_seconds_count{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])"
    }
   ]
  },
  {
   "title": "Async Read Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 140 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(zdm_async_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p50"
    },
    {
     "expr": "histogram_quantile(0.99, rate(zdm_async_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p99"
    },
    {
     "expr": "histogram_quantile(0.999, rate(zdm_async_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p999"
    },
    {
     "expr": "histogram_quantile(0.95, rate(zdm_async_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p95"
    },
    {
     "expr": "histogram_quantile(0.90, rate(zdm_async_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p90"
    },
    {
     "expr": "histogram_quantile(0.75, rate(zdm_async_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p75"
    }
   ]
  },
  {
   "title": "Async Read Latency Aggregate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 140 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(zdm_async_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(zdm_async_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(zdm_async_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p999"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(zdm_async_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(zdm_async_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(zdm_async_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
     "legendFormat": "p75"
    }
   ]
  },
  {
   "title": "Async Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 149 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zdm_async_connections_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}",
     "legendFormat": "async_connections {instance=\"{{instance}}\", node=\"{{node}}\"}"
    }
   ]
  },
  {
   "title": "Async Connections Sums",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 149 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(zdm_async_connections_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}) by (node)",
     "legendFormat": "async_connections {node=\"{{node}}\"}"
    },
    {
     "expr": "sum(zdm_async_connections_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}) by (instance)",
     "legendFormat": "async_connections {instance=\"{{instance}}\"}"
    }
   ]
  },
  {
   "title": "Async Error Rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 157 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(zdm_async_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate])",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\", error=\"{{error}}\"}"
    }
   ]
  },
  {
   "title": "Async Error Rate Sums",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 157 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (error) (rate(zdm_async_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate]))"
    },
    {
     "expr": "sum by (instance) (rate(zdm_async_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate]))"
    },
    {
     "expr": "sum by (node) (rate(zdm_async_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate]))"
    }
   ]
  },
  {
   "title": "Async Error Counters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 165 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zdm_async_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}",
     "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\", error=\"{{error}}\"}"
    }
   ]
  },
  {
   "title": "Async Error Counter Sums",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 165 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (error) (zdm_async_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"})"
    },
    {
     "expr": "sum by (instance) (zdm_async_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"})"
    },
    {
     "expr": "sum by (node) (zdm_async_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"})"
    }
   ]
  },
  {
   "title": "Async Error Rates by Instance and Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 173 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, node) (rate(zdm_async_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate]))"
    }
   ]
  },
  {
   "title": "Async Error Rates by Instance and Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 173 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, error) (rate(zdm_async_requests_failed_total{instance=~\"^($proxyinstance)$\", node=~\"^($node)$\"}[$error_rate]))"
    }
   ]
  },
  {
   "title": "Async Error Rates by Node and Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 173 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node, error) (rate(zdm_async_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate]))"
    }
   ]
  },
  {
   "title": "Async Error Counters by Instance and Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 181 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, node) (zdm_async_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"})"
    }
   ]
  },
  {
   "title": "Async Error Counters by Instance and Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 181 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, error) (zdm_async_requests_failed_total{instance=~\"^($proxyinstance)$\", node=~\"^($node)$\"})"
    }
   ]
  },
  {
   "title": "Async Error Counters by Node and Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 181 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node, error) (zdm_async_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"})"
    }
   ]
  }
 ]
}