---
style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/cloudalchemy/ansible-prometheus
options:
  tag_filter_pattern: '^[0-9]'
  commits:
  # filters:
  #   Type:
  #     - feat
  #     - fix
  #     - perf
  #     - refactor
  commit_groups:
  # title_maps:
  #   feat: Features
  #   fix: Bug Fixes
  #   perf: Performance Improvements
  #   refactor: Code Refactoring
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  merges:
    pattern: "(#\\w+)"
    pattern_maps:
      - Source
  notes:
    keywords:
      - BREAKING CHANGE
