---

- name: VECTOR | Ensure vector group
  group:
    name: "{{ vector_group }}"
    system: yes
    state: present

- name: VECTOR | Ensure vector user
  user:
    name: "{{ vector_user }}"
    group: "{{ vector_group }}"
    groups: "{{ vector_groups | default('') }}"
    system: yes
    shell: /usr/sbin/nologin
    createhome: no

- name: VECTOR | Ensure skeleton paths
  file:
    dest: "{{ item }}"
    owner: "{{ vector_user }}"
    group: "{{ vector_group }}"
    state: directory
  with_items:
    - "{{ vector_skeleton_paths }}"

- name: VECTOR | Check if vector has already been installed
  package: 
    name: "{{ vector_exec_name }}"
    state: present
  check_mode: yes 
  register: vector_check

- name: VECTOR | Download package
  apt:
    deb: "{{ vector_deb_package }}"
  when: vector_force_reinstall or not vector_check.changed or vector_version not in vector_check.stderr
