---
proxy_config_fragments_dir_path_name: /home/ubuntu/proxy_config_fragments

shared_assets_dir_path_name: /home/ubuntu/shared_assets

origin_scb_filename: origin_scb
target_scb_filename: target_scb

origin_astra_api_base_url: https://api.astra.datastax.com/
target_astra_api_base_url: https://api.astra.datastax.com/

origin_tls_proxy_dir_name: origin_tls
target_tls_proxy_dir_name: target_tls
