---
### Important note ###
### The configuration parameters in this file are only relevant when explicitly configuring TLS for self-managed clusters.
### Please ignore this file if only using Astra clusters or self-managed clusters that do not have either one-way TLS or Mutual TLS enabled.

### Proxy-to-Origin cluster TLS configuration

# Path to the directory, on the Ansible Control host, containing all TLS assets (Server CA Cert / Client cert / Client key) for the Origin cluster.
#origin_tls_user_dir_path_name:

# Origin cluster's Server CA certificate filename. Required for both one-way TLS and Mutual TLS.
#origin_tls_server_ca_filename:

# Filenames of the Client certificate and Client key that the proxy must present to the Origin cluster to enable TLS client authentication.
# Only required for Mutual TLS, in which case both must be specified.
#origin_tls_client_cert_filename:
#origin_tls_client_key_filename:

### Proxy-to-Target cluster TLS configuration

# Path to the directory, on the Ansible Control host, containing all TLS assets (Server CA Cert / Client cert / Client key) for the Target cluster
#target_tls_user_dir_path_name:

# Target cluster's Server CA certificate filename. Required for both one-way TLS and Mutual TLS.
#target_tls_server_ca_filename:

# Filenames of the Client certificate and Client key that the proxy must present to the Target cluster to enable TLS client authentication.
# Only required for Mutual TLS, in which case both must be specified.
#target_tls_client_cert_filename:
#target_tls_client_key_filename: