---

zdm_proxy_user_name: ubuntu
zdm_proxy_home_dir: /home/ubuntu

zdm_proxy_config_fragments_dir_name: zdm_proxy_config_fragments

zdm_proxy_shared_assets_dir_name: shared_assets

zdm_proxy_mutable_config_fragment_file_name: zdm_proxy_mutable_config.env
zdm_proxy_immutable_config_fragment_file_name: zdm_proxy_immutable_config.env
zdm_proxy_environment_config_file_name: zdm_proxy_config.env

origin_scb_file_name: origin_scb
target_scb_file_name: target_scb

origin_astra_api_base_url: https://api.astra.datastax.com/
target_astra_api_base_url: https://api.astra.datastax.com/

origin_tls_dest_dir_name: origin_tls
target_tls_dest_dir_name: target_tls
zdm_proxy_tls_dest_dir_name: proxy_tls

monitoring_user_name: ubuntu
monitoring_home_dir: /home/ubuntu

prometheus_config_dir_name: zdm_prometheus_config
grafana_config_dir_name: zdm_grafana_config
grafana_dashboards_dest_dir_name: zdm_grafana_dashboards