---
####################################
#### READ ROUTING CONFIGURATION ####
####################################

## Cluster currently considered as "primary" by the ZDM proxy. Valid values are ORIGIN (default) or TARGET.
## This is the current "source of truth" cluster.
## Reads are always sent synchronously to the primary cluster, and their results (or any errors) are returned to the client application.
primary_cluster: ORIGIN

## Read handling behaviour.
## Valid values: PRIMARY_ONLY (default behaviour: read synchronously from primary only) and DUAL_ASYNC_ON_SECONDARY (read synchronously from primary, and also asynchronously from secondary)
read_mode: PRIMARY_ONLY

#################
#### LOGGING ####
#################

## Proxy log level. Defaults to INFO. Setting it to DEBUG may have a small performance impact.
log_level: INFO
