---
grafana_version: 7.5.17
grafana_admin_user: admin
grafana_admin_password: testpasswordchangeme

prometheus_node_exporter_image: "prom/node-exporter:latest"
prometheus_node_exporter_container_name: "zdm-node-exporter-container"

prometheus_image: "prom/prometheus:latest"
prometheus_container_name: "zdm-prometheus-container"
prometheus_container_storage_volume: "zdm-prometheus-metrics-volume"
prometheus_web_listen_address: "{{ groups['monitoring'][0] }}:9090"
prometheus_evaluation_interval: 15s
prometheus_scrape_interval: 15s
prometheus_scrape_timeout: 10s
prometheus_environment_label_prefix: "zdm-monitoring"

grafana_image: "grafana/grafana:7.5.17"
grafana_container_name: "zdm-grafana-container"
