- name: Install system packages if required
  include_tasks: install_system_packages-centos.yml
  vars:
    - package_list: [ 'epel-release', 'curl', 'python2-pip', 'python2-setuptools' ]
  when: install_packages | bool

- name: Uninstall incompatible Docker-py Module
  become: no
  pip:
    name: docker-py
    state: absent

- name: Install Docker Module for Python
  pip:
    name:
    - docker==5.0.3
    - requests==2.18.2
