- name: Install system packages if required
  include_tasks: install_system_packages-centos.yml
  vars:
    - package_list: [ 'epel-release', 'curl', 'python3-pip', 'python3-setuptools', 'libselinux-python3', 'python2-pip' ]
  when: install_packages | bool

- name: Uninstall incompatible Docker-py Module
  become: yes
  pip:
    name: docker-py
    state: absent

- name: Install Docker Module for Python
  pip:
    name:
    - docker
  vars:
    ansible_python_interpreter: python3
