- name: yum update (this will take some time)
  yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ package_list }}"
  vars:
    ansible_python_interpreter: "/usr/bin/python2"
