- name: Install aptitude using apt (this will take some time)
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest

- name: Uninstall incompatible Docker-py Module
  become: no
  pip:
    name: docker-py
    state: absent

- name: Install Docker Module for Python
  pip:
    name: docker

# sudo groupadd docker
- name: Create "docker" group
  group:
    name: "docker"
    state: present

# sudo usermod -aG docker root
- name: Add OS user to "docker" group
  user:
    name: "{{ zdm_proxy_user_name }}"
    group: "docker"
    append: yes

# sudo chown -R ubuntu:docker /home/ubuntu/.docker
- name: Change ownership of Docker internal directory to this user and docker group
  file:
    path: "{{ zdm_proxy_home_dir }}/.docker"
    owner: "{{ zdm_proxy_user_name }}"
    group: "docker"
    recurse: yes