---
- name: Install Docker
  hosts: proxies
  become: yes

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

- name: Create directory to share assets between host and container
  hosts: proxies
  vars_files:
    - vars/proxy_advanced_config_input.yml

  tasks:
    - name: Create directory
      file:
        path: "{{ shared_assets_dir_path_name }}"
        state: directory

- name: Download Origin SCB
  hosts: proxies
  vars_files:
    - vars/proxy_core_config_input.yml
    - vars/proxy_advanced_config_input.yml

  tasks:
    - name: If Origin is Astra, call DevOps API to obtain the SCB URL, download it and save it in the configured location
      block: 
        - name: Query the Secure Connect Bundle location for Origin
          uri:
            url: "https://api.astra.datastax.com/v2/databases/{{ origin_astra_db_id }}/secureBundleURL"
            method: POST
            headers:
              Accept: "application/json"
              Content-Type: "application/json"
              Authorization: "Bearer {{ origin_astra_token }}"
            timeout: 30
            status_code: 200
          register: origin_scb_response
    
        - name: Create origin_scb directory in the shared_assets directory in the host's home
          file:
            path: "{{ shared_assets_dir_path_name }}/{{ origin_scb_dir_name }}"
            state: directory
          when:
            - origin_scb_response is defined

        - name: Download the Secure Connect Bundle for Origin using the URL from the response
          get_url: 
            url: "{{ origin_scb_response.json.downloadURL }}"
            dest: "{{ shared_assets_dir_path_name }}/{{ origin_scb_dir_name }}/origin_scb_{{ origin_astra_db_id }}.zip"
            timeout: 30
          when:
            - origin_scb_response is defined
      when:
        - origin_astra_token is defined
        - origin_astra_token | length > 0
        - origin_astra_db_id is defined
        - origin_astra_db_id | length > 0

- name: Download Target SCB
  hosts: proxies
  vars_files:
    - vars/proxy_core_config_input.yml
    - vars/proxy_advanced_config_input.yml
  
  tasks:
    - name: If Target is Astra, call DevOps API to obtain the SCB URL, download it and save it in the configured location
      block:
        - name: Query the Secure Connect Bundle location for Target
          uri:
            url: "https://api.astra.datastax.com/v2/databases/{{ target_astra_db_id }}/secureBundleURL"
            method: POST
            headers:
              Accept: "application/json"
              Content-Type: "application/json"
              Authorization: "Bearer {{ target_astra_token }}"
            timeout: 30
            status_code: 200
          register: target_scb_response

        - name: Create target_scb directory in the host's home
          file:
            path: "{{ shared_assets_dir_path_name }}/{{ target_scb_dir_name }}"
            state: directory
          when:
            - target_scb_response is defined

        - name: Download the Secure Connect Bundle for Target using the URL from the response
          get_url:
            url: "{{ target_scb_response.json.downloadURL }}"
            dest: "{{ shared_assets_dir_path_name }}/{{ target_scb_dir_name }}/target_scb_{{ target_astra_db_id }}.zip"
            timeout: 30
          when:
            - target_scb_response is defined
      when:
        - target_astra_token is defined
        - target_astra_token | length > 0
        - target_astra_db_id is defined
        - target_astra_db_id | length > 0

- name: Create proxy configuration env file
  hosts: proxies
  vars_files:
    - vars/proxy_core_config_input.yml
    - vars/proxy_advanced_config_input.yml

  tasks:
    - name: Generate env var file from template
      template: src=proxy_config.j2 dest=proxy_config.env 

- name: Install Proxy
  hosts: proxies
  become: yes
  vars_files:
    - vars/proxy_container.yml
    - vars/proxy_advanced_config_input.yml

  tasks:
    - name: Log into DockerHub
      community.docker.docker_login:
        username: "{{ cloudgate_image_repo_username }}"
        password: "{{ cloudgate_image_repo_password }}"

    - name: Pull Cloudgate Proxy Docker image
      docker_image:
        name: "{{ cloudgate_proxy_image }}"
        source: pull

    - name: Create proxy container
      docker_container:
        name: "{{ cloudgate_proxy_container_name }}"
        image: "{{ cloudgate_proxy_image }}"
        env_file: /home/ubuntu/proxy_config.env
        mounts:
          - source: "{{ shared_assets_dir_path_name }}" 
            target: "{{ shared_assets_dir_path_name }}"
            type: bind
        network_mode: host
        restart: yes
        state: started 




