---
- name: Create log collection directories on the control host
  hosts: "{{ log_collection_playbook_host }}"
  vars_files:
    - vars/zdm_proxy_log_collection_config.yml
    - vars/zdm_playbook_internal_config.yml

  tasks:
    - name: Create temporary log collection directory
      file:
        path: "{{ control_host_home_dir }}/{{ tmp_log_dir_name }}/"
        state: directory
    - name: Create log archive directory
      file:
        path: "{{ control_host_home_dir }}/{{ archived_log_dir_name }}/"
        state: directory

- name: Collect all ZDM proxy logs
  hosts: proxies
  become: yes
  vars_files:
    - vars/zdm_proxy_container_config.yml
    - vars/zdm_proxy_log_collection_config.yml
    - vars/zdm_playbook_internal_config.yml

  tasks:
    - name: Inspect the ZDM proxy container
      docker_container_info:
        name: "{{ zdm_proxy_container_name }}"
      register: containerinfo
    - name: Find the log files to copy/fetch
      find:
        paths: "/var/lib/docker/containers/{{ containerinfo.container.Id }}"
        patterns: ".*-json.log$"
        use_regex: yes
      register: logfilenames
      when:
        - containerinfo is defined
    - name: Fetch the logs of the container, copying them to the temporary log collection direcotry on the control host
      fetch:
        src: "{{ item.path }}"
        dest: "{{ control_host_home_dir }}/{{ tmp_log_dir_name }}/"
        flat: yes
      with_items: "{{ logfilenames.files }}"

- name: Zip the logs in a single archive
  hosts: "{{ log_collection_playbook_host }}"
  vars_files:
    - vars/zdm_proxy_log_collection_config.yml
    - vars/zdm_playbook_internal_config.yml

  tasks:
    - name: Create the zip archive
      community.general.archive:
        path: "{{ control_host_home_dir }}/{{ tmp_log_dir_name }}/"
        dest: "{{ control_host_home_dir }}/{{ archived_log_dir_name }}/zdm_proxy_logs_{{ ansible_date_time.iso8601_basic_short }}.zip"
        format: zip
    - name: Remove the temporary directory where the logs were copied on the control host
      file:
        path: "{{ control_host_home_dir }}/{{ tmp_log_dir_name }}/"
        state: absent
