---

- name: Create proxy configuration env file based on the latest configuration
  hosts: proxies
  vars_files:
    - vars/proxy_core_config_input.yml
    - vars/proxy_advanced_config_input.yml
    - vars/playbook_internal_config.yml

  tasks:
    - name: Generate env var file from template for mutable configuration
      template:
        src: "proxy_mutable_config.j2"
        dest: "{{ proxy_config_fragments_dir_path_name }}/proxy_mutable_config.env"
    - name: Merge the immutable and mutable configuration files into a single one
      assemble:
        src: "{{ proxy_config_fragments_dir_path_name }}"
        dest: /home/ubuntu/proxy_config.env

- name: Configure and restart proxy
  hosts: proxies
  serial: 1
  become: yes
  vars_files:
    - vars/proxy_container.yml
    - vars/proxy_advanced_config_input.yml
    - vars/playbook_internal_config.yml

  tasks:
    - name: Create proxy container with updated configuration
      docker_container:
        name: "{{ cloudgate_proxy_container_name }}"
        image: "{{ cloudgate_proxy_image }}"
        env_file: /home/ubuntu/proxy_config.env
        mounts:
          - source: "{{ shared_assets_dir_path_name }}"
            target: "{{ shared_assets_dir_path_name }}"
            type: bind
        network_mode: host
        restart_policy: unless-stopped
        restart: yes
        state: started
    - name: "Wait for the proxy to come up"
      uri:
        url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ proxy_metrics_port }}/health/readiness"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 6
      delay: 5
    - pause:
        prompt: "Pause for 10s after restarting this proxy"
        seconds: 10



