---

- name: Do a rolling restart of all ZDM proxies. This operation does not apply any configuration changes.
  hosts: proxies
  serial: 1
  become: yes
  vars_files:
    - vars/zdm_proxy_container_config.yml
    - vars/zdm_proxy_advanced_config.yml
    - vars/zdm_playbook_internal_config.yml
    - vars/zdm_proxy_cluster_config.yml

  tasks:
    - name: Stop one ZDM proxy instance at a time
      docker_container:
        name: "{{ zdm_proxy_container_name }}"
        state: stopped
    - name: Start that ZDM proxy instance
      docker_container:
        name: "{{ zdm_proxy_container_name }}"
        state: started
    - name: Wait for this ZDM proxy to come up
      uri:
        url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ metrics_port }}/health/readiness"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 6
      delay: 5
    - pause:
        prompt: "Pause for {{ pause_between_restarts_in_seconds }} seconds after restarting this ZDM proxy instance"
        seconds: "{{ pause_between_restarts_in_seconds }}"



