---

- name: Do a rolling restart of the proxy
  hosts: proxies
  serial: 1
  become: yes
  vars_files:
    - vars/proxy_container.yml
    - vars/proxy_advanced_config_input.yml

  tasks:
    - name: Restart one proxy instance at a time
      docker_container:
        name: "{{ cloudgate_proxy_container_name }}"
        restart: yes
        state: started
    - name: "Wait for the proxy to come up"
      uri:
        url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ proxy_metrics_port }}/health/readiness"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 6
      delay: 5
    - pause:
        prompt: "Pause for 10s after restarting this proxy"
        seconds: 10



