---

## General
# Version
vector_version: 0.10.0
vector_package_architecture: amd64

# Deb
vector_deb_package: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_package_architecture }}.deb"

# Set true to force the download and installation of the package
vector_force_reinstall: false

# Paths
vector_bin_path: "/usr/bin"
vector_skeleton_paths:
  - "{{ vector_bin_path }}"
vector_exec_name: vector

## Service options
# Documentation
vector_documentation_link: https://vector.dev/docs/about/what-is-vector/

# Owner
vector_user: vector
vector_group: vector
# Maybe you will need some extra groups for user vector
# vector_groups: []

# Start on boot
vector_service_enabled: true
# Current state: started, stopped
vector_service_state: started

# Logs
# If wanted to output the logs to a file define the following variable
# More information at https://www.freedesktop.org/software/systemd/man/systemd.exec.html#StandardOutput=
vector_log_output: journal

vector_config_template_path: "vector.toml.j2"
vector_service_template_path: "vector.service.j2"

vector_data_dir: "/var/lib/vector"
# vector_syslog_identifier: vector
